import type { MultiLanguageString } from 'interfaces/IProduct';

export interface ICountry {
  translations: MultiLanguageString;
  flag: string;
  callingCode: string;
  phoneFormat: string | string[];
}

const countriesList: ICountry[] = [
  {
    translations: {
      en: 'Afghanistan',
      sv: 'Afghanistan',
      de: 'Afghanistan',
      fr: 'Afghanistan',
      es: 'Afganistán',
      ru: 'Афганистан',
      uk: 'Афганістан',
      pl: 'Afganistan',
    },
    flag: 'https://flagcdn.com/w320/af.png',
    callingCode: '+93',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Albania',
      sv: 'Albanien',
      de: 'Albanien',
      fr: 'Albanie',
      es: 'Albania',
      ru: 'Албания',
      uk: 'Албанія',
      pl: 'Albania',
    },
    flag: 'https://flagcdn.com/w320/al.png',
    callingCode: '+355',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Algeria',
      sv: 'Algeriet',
      de: 'Algerien',
      fr: 'Algérie',
      es: 'Argelia',
      ru: 'Алжир',
      uk: 'Алжир',
      pl: 'Algieria',
    },
    flag: 'https://flagcdn.com/w320/dz.png',
    callingCode: '+213',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Andorra',
      sv: 'Andorra',
      de: 'Andorra',
      fr: 'Andorre',
      es: 'Andorra',
      ru: 'Андорра',
      uk: 'Андорра',
      pl: 'Andora',
    },
    flag: 'https://flagcdn.com/w320/ad.png',
    callingCode: '+376',
    phoneFormat: '###-###',
  },
  {
    translations: {
      en: 'Angola',
      sv: 'Angola',
      de: 'Angola',
      fr: 'Angola',
      es: 'Angola',
      ru: 'Ангола',
      uk: 'Ангола',
      pl: 'Angola',
    },
    flag: 'https://flagcdn.com/w320/ao.png',
    callingCode: '+244',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Antigua and Barbuda',
      sv: 'Antigua och Barbuda',
      de: 'Antigua und Barbuda',
      fr: 'Antigua-et-Barbuda',
      es: 'Antigua y Barbuda',
      ru: 'Антигуа и Барбуда',
      uk: 'Антигуа і Барбуда',
      pl: 'Antigua i Barbuda',
    },
    flag: 'https://flagcdn.com/w320/ag.png',
    callingCode: '+1268',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Argentina',
      sv: 'Argentina',
      de: 'Argentinien',
      fr: 'Argentine',
      es: 'Argentina',
      ru: 'Аргентина',
      uk: 'Аргентина',
      pl: 'Argentyna',
    },
    flag: 'https://flagcdn.com/w320/ar.png',
    callingCode: '+54',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Armenia',
      sv: 'Armenien',
      de: 'Armenien',
      fr: 'Arménie',
      es: 'Armenia',
      ru: 'Армения',
      uk: 'Вірменія',
      pl: 'Armenia',
    },
    flag: 'https://flagcdn.com/w320/am.png',
    callingCode: '+374',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Aruba',
      sv: 'Aruba',
      de: 'Aruba',
      fr: 'Aruba',
      es: 'Aruba',
      ru: 'Аруба',
      uk: 'Аруба',
      pl: 'Aruba',
    },
    flag: 'https://flagcdn.com/w320/aw.png',
    callingCode: '+297',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Australia',
      sv: 'Australien',
      de: 'Australien',
      fr: 'Australie',
      es: 'Australia',
      ru: 'Австралия',
      uk: 'Австралія',
      pl: 'Australia',
    },
    flag: 'https://flagcdn.com/w320/au.png',
    callingCode: '+61',
    phoneFormat: '#-####-####',
  },
  {
    translations: {
      en: 'Austria',
      sv: 'Österrike',
      de: 'Österreich',
      fr: 'Autriche',
      es: 'Austria',
      ru: 'Австрия',
      uk: 'Австрія',
      pl: 'Austria',
    },
    flag: 'https://flagcdn.com/w320/at.png',
    callingCode: '+43',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Azerbaijan',
      sv: 'Azerbajdzjan',
      de: 'Aserbaidschan',
      fr: 'Azerbaïdjan',
      es: 'Azerbaiyán',
      ru: 'Азербайджан',
      uk: 'Азербайджан',
      pl: 'Azerbejdżan',
    },
    flag: 'https://flagcdn.com/w320/az.png',
    callingCode: '+994',
    phoneFormat: '##-###-##-##',
  },
  {
    translations: {
      en: 'Bahamas',
      sv: 'Bahamas',
      de: 'Bahamas',
      fr: 'Bahamas',
      es: 'Bahamas',
      ru: 'Багамы',
      uk: 'Багами',
      pl: 'Bahamy',
    },
    flag: 'https://flagcdn.com/w320/bs.png',
    callingCode: '+1242',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Bahrain',
      sv: 'Bahrain',
      de: 'Bahrain',
      fr: 'Bahreïn',
      es: 'Baréin',
      ru: 'Бахрейн',
      uk: 'Бахрейн',
      pl: 'Bahrajn',
    },
    flag: 'https://flagcdn.com/w320/bh.png',
    callingCode: '+973',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Bangladesh',
      sv: 'Bangladesh',
      de: 'Bangladesch',
      fr: 'Bangladesh',
      es: 'Bangladés',
      ru: 'Бангладеш',
      uk: 'Бангладеш',
      pl: 'Bangladesz',
    },
    flag: 'https://flagcdn.com/w320/bd.png',
    callingCode: '+880',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Barbados',
      sv: 'Barbados',
      de: 'Barbados',
      fr: 'Barbade',
      es: 'Barbados',
      ru: 'Барбадос',
      uk: 'Барбадос',
      pl: 'Barbados',
    },
    flag: 'https://flagcdn.com/w320/bb.png',
    callingCode: '+1246',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Belarus',
      sv: 'Belarus',
      de: 'Belarus',
      fr: 'Biélorussie',
      es: 'Bielorrusia',
      ru: 'Беларусь',
      uk: 'Білорусь',
      pl: 'Białoruś',
    },
    flag: 'https://flagcdn.com/w320/by.png',
    callingCode: '+375',
    phoneFormat: '(##)###-##-##',
  },
  {
    translations: {
      en: 'Belgium',
      sv: 'Belgien',
      de: 'Belgien',
      fr: 'Belgique',
      es: 'Bélgica',
      ru: 'Бельгия',
      uk: 'Бельгія',
      pl: 'Belgia',
    },
    flag: 'https://flagcdn.com/w320/be.png',
    callingCode: '+32',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Belize',
      sv: 'Belize',
      de: 'Belize',
      fr: 'Belize',
      es: 'Belice',
      ru: 'Белиз',
      uk: 'Беліз',
      pl: 'Belize',
    },
    flag: 'https://flagcdn.com/w320/bz.png',
    callingCode: '+501',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Benin',
      sv: 'Benin',
      de: 'Benin',
      fr: 'Bénin',
      es: 'Benín',
      ru: 'Бенин',
      uk: 'Бенін',
      pl: 'Benin',
    },
    flag: 'https://flagcdn.com/w320/bj.png',
    callingCode: '+22#',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Bhutan',
      sv: 'Bhutan',
      de: 'Bhutan',
      fr: 'Bhoutan',
      es: 'Bután',
      ru: 'Бутан',
      uk: 'Бутан',
      pl: 'Bhutan',
    },
    flag: 'https://flagcdn.com/w320/bt.png',
    callingCode: '+975',
    phoneFormat: ['17-###-###', '#-###-###'],
  },
  {
    translations: {
      en: 'Bolivia',
      sv: 'Bolivia',
      de: 'Bolivien',
      fr: 'Bolivie',
      es: 'Bolivia',
      ru: 'Боливия',
      uk: 'Болівія',
      pl: 'Boliwia',
    },
    flag: 'https://flagcdn.com/w320/bo.png',
    callingCode: '+591',
    phoneFormat: '#-###-####',
  },
  {
    translations: {
      en: 'Bosnia and Herzegovina',
      sv: 'Bosnien och Hercegovina',
      de: 'Bosnien und Herzegowina',
      fr: 'Bosnie-Herzégovine',
      es: 'Bosnia y Herzegovina',
      ru: 'Босния и Герцеговина',
      uk: 'Боснія і Герцеговина',
      pl: 'Bośnia i Hercegowina',
    },
    flag: 'https://flagcdn.com/w320/ba.png',
    callingCode: '+387',
    phoneFormat: ['##-#####', '##-####'],
  },
  {
    translations: {
      en: 'Botswana',
      sv: 'Botswana',
      de: 'Botswana',
      fr: 'Botswana',
      es: 'Botsuana',
      ru: 'Ботсвана',
      uk: 'Ботсвана',
      pl: 'Botswana',
    },
    flag: 'https://flagcdn.com/w320/bw.png',
    callingCode: '+267',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Brazil',
      sv: 'Brasilien',
      de: 'Brasilien',
      fr: 'Brésil',
      es: 'Brasil',
      ru: 'Бразилия',
      uk: 'Бразилія',
      pl: 'Brazylia',
    },
    flag: 'https://flagcdn.com/w320/br.png',
    callingCode: '+55',
    phoneFormat: ['(##)####-####', '(##)7###-####', '(##)9####-####'],
  },
  {
    translations: {
      en: 'British Indian Ocean Territory',
      sv: 'Brittiska Indiska oceanen territorium',
      de: 'Britisches Territorium im Indischen Ozean',
      fr: "Territoire britannique de l'océan Indien",
      es: 'Territorio Británico del Océano Índico',
      ru: 'Британская территория в Индийском океане',
      uk: 'Британська територія в Індійському океані',
      pl: 'Brytyjskie Terytorium Oceanu Indyjskiego',
    },
    flag: 'https://flagcdn.com/w320/io.png',
    callingCode: '+246',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Brunei',
      sv: 'Brunei',
      de: 'Brunei',
      fr: 'Brunei',
      es: 'Brunéi',
      ru: 'Бруней',
      uk: 'Бруней',
      pl: 'Brunei',
    },
    flag: 'https://flagcdn.com/w320/bn.png',
    callingCode: '+673',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Bulgaria',
      sv: 'Bulgarien',
      de: 'Bulgarien',
      fr: 'Bulgarie',
      es: 'Bulgaria',
      ru: 'Болгария',
      uk: 'Болгарія',
      pl: 'Bułgaria',
    },
    flag: 'https://flagcdn.com/w320/bg.png',
    callingCode: '+359',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Burkina Faso',
      sv: 'Burkina Faso',
      de: 'Burkina Faso',
      fr: 'Burkina Faso',
      es: 'Burkina Faso',
      ru: 'Буркина-Фасо',
      uk: 'Буркіна-Фасо',
      pl: 'Burkina Faso',
    },
    flag: 'https://flagcdn.com/w320/bf.png',
    callingCode: '+226',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Burundi',
      sv: 'Burundi',
      de: 'Burundi',
      fr: 'Burundi',
      es: 'Burundi',
      ru: 'Бурунди',
      uk: 'Бурунді',
      pl: 'Burundi',
    },
    flag: 'https://flagcdn.com/w320/bi.png',
    callingCode: '+257',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Cambodia',
      sv: 'Kambodja',
      de: 'Kambodscha',
      fr: 'Cambodge',
      es: 'Camboya',
      ru: 'Камбоджа',
      uk: 'Камбоджа',
      pl: 'Kambodża',
    },
    flag: 'https://flagcdn.com/w320/kh.png',
    callingCode: '+855',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Cameroon',
      sv: 'Kamerun',
      de: 'Kamerun',
      fr: 'Cameroun',
      es: 'Camerún',
      ru: 'Камерун',
      uk: 'Камерун',
      pl: 'Kamerun',
    },
    flag: 'https://flagcdn.com/w320/cm.png',
    callingCode: '+237',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Canada',
      sv: 'Kanada',
      de: 'Kanada',
      fr: 'Canada',
      es: 'Canadá',
      ru: 'Канада',
      uk: 'Канада',
      pl: 'Kanada',
    },
    flag: 'https://flagcdn.com/w320/ca.png',
    callingCode: '+1',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Cape Verde',
      sv: 'Kap Verde',
      de: 'Kap Verde',
      fr: 'Cap-Vert',
      es: 'Cabo Verde',
      ru: 'Кабо-Верде',
      uk: 'Кабо-Верде',
      pl: 'Republika Zielonego Przylądka',
    },
    flag: 'https://flagcdn.com/w320/cv.png',
    callingCode: '+238',
    phoneFormat: '(###)##-##',
  },
  {
    translations: {
      en: 'Caribbean Netherlands',
      sv: 'Karibiska Nederländerna',
      de: 'Karibische Niederlande',
      fr: 'Pays-Bas caribéens',
      es: 'Países Bajos caribeños',
      ru: 'Карибские Нидерланды',
      uk: 'Карибські Нідерланди',
      pl: 'Niderlandy Karaibskie',
    },
    flag: 'https://flagcdn.com/w320/bq.png',
    callingCode: '+599',
    phoneFormat: '###-###',
  },
  {
    translations: {
      en: 'Cayman Islands',
      sv: 'Caymanöarna',
      de: 'Kaimaninseln',
      fr: 'Îles Caïmans',
      es: 'Islas Caimán',
      ru: 'Каймановы Острова',
      uk: 'Кайманові Острови',
      pl: 'Kajmany',
    },
    flag: 'https://flagcdn.com/w320/ky.png',
    callingCode: '+1345',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Central African Republic',
      sv: 'Centralafrikanska republiken',
      de: 'Zentralafrikanische Republik',
      fr: 'République centrafricaine',
      es: 'República Centroafricana',
      ru: 'Центральноафриканская Республика',
      uk: 'Центральноафриканська Республіка',
      pl: 'Republika Środkowoafrykańska',
    },
    flag: 'https://flagcdn.com/w320/cf.png',
    callingCode: '+236',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Chad',
      sv: 'Tchad',
      de: 'Tschad',
      fr: 'Tchad',
      es: 'Chad',
      ru: 'Чад',
      uk: 'Чад',
      pl: 'Czad',
    },
    flag: 'https://flagcdn.com/w320/td.png',
    callingCode: '+235',
    phoneFormat: '##-##-##-##',
  },
  {
    translations: {
      en: 'Chile',
      sv: 'Chile',
      de: 'Chile',
      fr: 'Chili',
      es: 'Chile',
      ru: 'Чили',
      uk: 'Чилі',
      pl: 'Chile',
    },
    flag: 'https://flagcdn.com/w320/cl.png',
    callingCode: '+56',
    phoneFormat: '#-####-####',
  },
  {
    translations: {
      en: 'China',
      sv: 'Kina',
      de: 'China',
      fr: 'Chine',
      es: 'China',
      ru: 'Китай',
      uk: 'Китай',
      pl: 'Chiny',
    },
    flag: 'https://flagcdn.com/w320/cn.png',
    callingCode: '+86',
    phoneFormat: '000 0000 0000',
  },
  {
    translations: {
      en: 'Colombia',
      sv: 'Colombia',
      de: 'Kolumbien',
      fr: 'Colombie',
      es: 'Colombia',
      ru: 'Колумбия',
      uk: 'Колумбія',
      pl: 'Kolumbia',
    },
    flag: 'https://flagcdn.com/w320/co.png',
    callingCode: '+57',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Comoros',
      sv: 'Komorerna',
      de: 'Komoren',
      fr: 'Comores',
      es: 'Comoras',
      ru: 'Коморы',
      uk: 'Комори',
      pl: 'Komory',
    },
    flag: 'https://flagcdn.com/w320/km.png',
    callingCode: '+269',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Congo',
      sv: 'Kongo',
      de: 'Kongo',
      fr: 'Congo',
      es: 'Congo',
      ru: 'Конго',
      uk: 'Конго',
      pl: 'Kongo',
    },
    flag: 'https://flagcdn.com/w320/cg.png',
    callingCode: '+242',
    phoneFormat: '##-##-##',
  },
  {
    translations: {
      en: 'Democratic Republic of the Congo',
      sv: 'Demokratiska republiken Kongo',
      de: 'Demokratische Republik Kongo',
      fr: 'République démocratique du Congo',
      es: 'República Democrática del Congo',
      ru: 'Демократическая Республика Конго',
      uk: 'Демократична Республіка Конго',
      pl: 'Demokratyczna Republika Konga',
    },
    flag: 'https://flagcdn.com/w320/cd.png',
    callingCode: '+243',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Costa Rica',
      sv: 'Costa Rica',
      de: 'Costa Rica',
      fr: 'Costa Rica',
      es: 'Costa Rica',
      ru: 'Коста-Рика',
      uk: 'Коста-Ріка',
      pl: 'Kostaryka',
    },
    flag: 'https://flagcdn.com/w320/cr.png',
    callingCode: '+506',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: "Côte d'Ivoire",
      sv: 'Elfenbenskusten',
      de: 'Elfenbeinküste',
      fr: "Côte d'Ivoire",
      es: 'Costa de Marfil',
      ru: "Кот-д'Ивуар",
      uk: 'Кот-д’Івуар',
      pl: 'Wybrzeże Kości Słoniowej',
    },
    flag: 'https://flagcdn.com/w320/ci.png',
    callingCode: '+225',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Croatia',
      sv: 'Kroatien',
      de: 'Kroatien',
      fr: 'Croatie',
      es: 'Croacia',
      ru: 'Хорватия',
      uk: 'Хорватія',
      pl: 'Chorwacja',
    },
    flag: 'https://flagcdn.com/w320/hr.png',
    callingCode: '+385',
    phoneFormat: '###-###-###',
  },
  {
    translations: {
      en: 'Cuba',
      sv: 'Kuba',
      de: 'Kuba',
      fr: 'Cuba',
      es: 'Cuba',
      ru: 'Куба',
      uk: 'Куба',
      pl: 'Kuba',
    },
    flag: 'https://flagcdn.com/w320/cu.png',
    callingCode: '+53',
    phoneFormat: '###-###-###',
  },
  {
    translations: {
      en: 'Curaçao',
      sv: 'Curaçao',
      de: 'Curaçao',
      fr: 'Curaçao',
      es: 'Curaçao',
      ru: 'Кюрасао',
      uk: 'Кюрасао',
      pl: 'Curaçao',
    },
    flag: 'https://flagcdn.com/w320/cw.png',
    callingCode: '+599',
    phoneFormat: '###-###',
  },
  {
    translations: {
      en: 'Cyprus',
      sv: 'Cypern',
      de: 'Zypern',
      fr: 'Chypre',
      es: 'Chipre',
      ru: 'Кипр',
      uk: 'Кіпр',
      pl: 'Cypr',
    },
    flag: 'https://flagcdn.com/w320/cy.png',
    callingCode: '+357',
    phoneFormat: '###-###-###',
  },
  {
    translations: {
      en: 'Czech Republic',
      sv: 'Tjeckien',
      de: 'Tschechische Republik',
      fr: 'République tchèque',
      es: 'República Checa',
      ru: 'Чехия',
      uk: 'Чехія',
      pl: 'Czechy',
    },
    flag: 'https://flagcdn.com/w320/cz.png',
    callingCode: '+420',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Denmark',
      sv: 'Danmark',
      de: 'Dänemark',
      fr: 'Danemark',
      es: 'Dinamarca',
      ru: 'Дания',
      uk: 'Данія',
      pl: 'Dania',
    },
    flag: 'https://flagcdn.com/w320/dk.png',
    callingCode: '+45',
    phoneFormat: '##-##-##-##',
  },
  {
    translations: {
      en: 'Djibouti',
      sv: 'Djibouti',
      de: 'Dschibuti',
      fr: 'Djibouti',
      es: 'Yibuti',
      ru: 'Джибути',
      uk: 'Джибуті',
      pl: 'Dżibuti',
    },
    flag: 'https://flagcdn.com/w320/dj.png',
    callingCode: '+253',
    phoneFormat: '##-##-##',
  },
  {
    translations: {
      en: 'Dominica',
      sv: 'Dominika',
      de: 'Dominica',
      fr: 'Dominique',
      es: 'Dominica',
      ru: 'Доминика',
      uk: 'Домініка',
      pl: 'Dominika',
    },
    flag: 'https://flagcdn.com/w320/dm.png',
    callingCode: '+1767',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Dominican Republic',
      sv: 'Dominikanska republiken',
      de: 'Dominikanische Republik',
      fr: 'République dominicaine',
      es: 'República Dominicana',
      ru: 'Доминиканская Республика',
      uk: 'Домініканська Республіка',
      pl: 'Dominikana',
    },
    flag: 'https://flagcdn.com/w320/do.png',
    callingCode: '+1809',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Ecuador',
      sv: 'Ecuador',
      de: 'Ecuador',
      fr: 'Équateur',
      es: 'Ecuador',
      ru: 'Эквадор',
      uk: 'Еквадор',
      pl: 'Ekwador',
    },
    flag: 'https://flagcdn.com/w320/ec.png',
    callingCode: '+593',
    phoneFormat: '###-###-###',
  },
  {
    translations: {
      en: 'Egypt',
      sv: 'Egypten',
      de: 'Ägypten',
      fr: 'Égypte',
      es: 'Egipto',
      ru: 'Египет',
      uk: 'Єгипет',
      pl: 'Egipt',
    },
    flag: 'https://flagcdn.com/w320/eg.png',
    callingCode: '+20',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'El Salvador',
      sv: 'El Salvador',
      de: 'El Salvador',
      fr: 'El Salvador',
      es: 'El Salvador',
      ru: 'Сальвадор',
      uk: 'Сальвадор',
      pl: 'Salwador',
    },
    flag: 'https://flagcdn.com/w320/sv.png',
    callingCode: '+503',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Equatorial Guinea',
      sv: 'Ekvatorialguinea',
      de: 'Äquatorialguinea',
      fr: 'Guinée équatoriale',
      es: 'Guinea Ecuatorial',
      ru: 'Экваториальная Гвинея',
      uk: 'Екваторіальна Гвінея',
      pl: 'Gwinea Równikowa',
    },
    flag: 'https://flagcdn.com/w320/gq.png',
    callingCode: '+240',
    phoneFormat: '##-##-##',
  },
  {
    translations: {
      en: 'Eritrea',
      sv: 'Eritrea',
      de: 'Eritrea',
      fr: 'Érythrée',
      es: 'Eritrea',
      ru: 'Эритрея',
      uk: 'Еритрея',
      pl: 'Erytrea',
    },
    flag: 'https://flagcdn.com/w320/er.png',
    callingCode: '+291',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Estonia',
      sv: 'Estland',
      de: 'Estland',
      fr: 'Estonie',
      es: 'Estonia',
      ru: 'Эстония',
      uk: 'Естонія',
      pl: 'Estonia',
    },
    flag: 'https://flagcdn.com/w320/ee.png',
    callingCode: '+372',
    phoneFormat: '000 0000',
  },
  {
    translations: {
      en: 'Ethiopia',
      sv: 'Etiopien',
      de: 'Äthiopien',
      fr: 'Éthiopie',
      es: 'Etiopía',
      ru: 'Эфиопия',
      uk: 'Ефіопія',
      pl: 'Etiopia',
    },
    flag: 'https://flagcdn.com/w320/et.png',
    callingCode: '+251',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Fiji',
      sv: 'Fiji',
      de: 'Fidschi',
      fr: 'Fidji',
      es: 'Fiyi',
      ru: 'Фиджи',
      uk: 'Фіджі',
      pl: 'Fidżi',
    },
    flag: 'https://flagcdn.com/w320/fj.png',
    callingCode: '+679',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Finland',
      sv: 'Finland',
      de: 'Finnland',
      fr: 'Finlande',
      es: 'Finlandia',
      ru: 'Финляндия',
      uk: 'Фінляндія',
      pl: 'Finlandia',
    },
    flag: 'https://flagcdn.com/w320/fi.png',
    callingCode: '+358',
    phoneFormat: '(###)###-##-##',
  },
  {
    translations: {
      en: 'France',
      sv: 'Frankrike',
      de: 'Frankreich',
      fr: 'France',
      es: 'Francia',
      ru: 'Франция',
      uk: 'Франція',
      pl: 'Francja',
    },
    flag: 'https://flagcdn.com/w320/fr.png',
    callingCode: '+33',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'French Guiana',
      sv: 'Franska Guyana',
      de: 'Französisch-Guayana',
      fr: 'Guyane française',
      es: 'Guayana Francesa',
      ru: 'Французская Гвиана',
      uk: 'Французька Гвіана',
      pl: 'Gujana Francuska',
    },
    flag: 'https://flagcdn.com/w320/gf.png',
    callingCode: '+594',
    phoneFormat: '###-##-##',
  },
  {
    translations: {
      en: 'French Polynesia',
      sv: 'Franska Polynesien',
      de: 'Französisch-Polynesien',
      fr: 'Polynésie française',
      es: 'Polinesia Francesa',
      ru: 'Французская Полинезия',
      uk: 'Французька Полінезія',
      pl: 'Polinezja Francuska',
    },
    flag: 'https://flagcdn.com/w320/pf.png',
    callingCode: '+689',
    phoneFormat: '##-##-##',
  },
  {
    translations: {
      en: 'Gabon',
      sv: 'Gabon',
      de: 'Gabun',
      fr: 'Gabon',
      es: 'Gabón',
      ru: 'Габон',
      uk: 'Габон',
      pl: 'Gabon',
    },
    flag: 'https://flagcdn.com/w320/ga.png',
    callingCode: '+241',
    phoneFormat: '#-##-##-##',
  },
  {
    translations: {
      en: 'Gambia',
      sv: 'Gambia',
      de: 'Gambia',
      fr: 'Gambie',
      es: 'Gambia',
      ru: 'Гамбия',
      uk: 'Гамбія',
      pl: 'Gambia',
    },
    flag: 'https://flagcdn.com/w320/gm.png',
    callingCode: '+220',
    phoneFormat: '(###)##-##',
  },
  {
    translations: {
      en: 'Georgia',
      sv: 'Georgien',
      de: 'Georgien',
      fr: 'Géorgie',
      es: 'Georgia',
      ru: 'Грузия',
      uk: 'Грузія',
      pl: 'Gruzja',
    },
    flag: 'https://flagcdn.com/w320/ge.png',
    callingCode: '+995',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Germany',
      sv: 'Tyskland',
      de: 'Deutschland',
      fr: 'Allemagne',
      es: 'Alemania',
      ru: 'Германия',
      uk: 'Німеччина',
      pl: 'Niemcy',
    },
    flag: 'https://flagcdn.com/w320/de.png',
    callingCode: '+49',
    phoneFormat: [
      '(####)###-####',
      '(###)###-####',
      '(###)##-####',
      '(###)##-###',
      '(###)##-##',
      '###-###',
    ],
  },
  {
    translations: {
      en: 'Ghana',
      sv: 'Ghana',
      de: 'Ghana',
      fr: 'Ghana',
      es: 'Ghana',
      ru: 'Гана',
      uk: 'Гана',
      pl: 'Ghana',
    },
    flag: 'https://flagcdn.com/w320/gh.png',
    callingCode: '+233',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Greece',
      sv: 'Grekland',
      de: 'Griechenland',
      fr: 'Grèce',
      es: 'Grecia',
      ru: 'Греция',
      uk: 'Греція',
      pl: 'Grecja',
    },
    flag: 'https://flagcdn.com/w320/gr.png',
    callingCode: '+30',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Greenland',
      sv: 'Grönland',
      de: 'Grönland',
      fr: 'Groenland',
      es: 'Groenlandia',
      ru: 'Гренландия',
      uk: 'Гренландія',
      pl: 'Grenlandia',
    },
    flag: 'https://flagcdn.com/w320/gl.png',
    callingCode: '+299',
    phoneFormat: '##-##-##',
  },
  {
    translations: {
      en: 'Grenada',
      sv: 'Grenada',
      de: 'Grenada',
      fr: 'Grenade',
      es: 'Granada',
      ru: 'Гренада',
      uk: 'Гренада',
      pl: 'Grenada',
    },
    flag: 'https://flagcdn.com/w320/gd.png',
    callingCode: '+1473',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Guadeloupe',
      sv: 'Guadeloupe',
      de: 'Guadeloupe',
      fr: 'Guadeloupe',
      es: 'Guadalupe',
      ru: 'Гваделупа',
      uk: 'Гваделупа',
      pl: 'Gwadelupa',
    },
    flag: 'https://flagcdn.com/w320/gp.png',
    callingCode: '+590',
    phoneFormat: '###-##-##',
  },
  {
    translations: {
      en: 'Guam',
      sv: 'Guam',
      de: 'Guam',
      fr: 'Guam',
      es: 'Guam',
      ru: 'Гуам',
      uk: 'Гуам',
      pl: 'Guam',
    },
    flag: 'https://flagcdn.com/w320/gu.png',
    callingCode: '+1671',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Guatemala',
      sv: 'Guatemala',
      de: 'Guatemala',
      fr: 'Guatemala',
      es: 'Guatemala',
      ru: 'Гватемала',
      uk: 'Гватемала',
      pl: 'Gwatemala',
    },
    flag: 'https://flagcdn.com/w320/gt.png',
    callingCode: '+502',
    phoneFormat: '#-###-####',
  },
  {
    translations: {
      en: 'Guinea',
      sv: 'Guinea',
      de: 'Guinea',
      fr: 'Guinée',
      es: 'Guinea',
      ru: 'Гвинея',
      uk: 'Гвінея',
      pl: 'Gwinea',
    },
    flag: 'https://flagcdn.com/w320/gn.png',
    callingCode: '+224',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Guinea-Bissau',
      sv: 'Guinea-Bissau',
      de: 'Guinea-Bissau',
      fr: 'Guinée-Bissau',
      es: 'Guinea-Bisáu',
      ru: 'Гвинея-Бисау',
      uk: 'Гвінея-Бісау',
      pl: 'Gwinea Bissau',
    },
    flag: 'https://flagcdn.com/w320/gw.png',
    callingCode: '+245',
    phoneFormat: '#-######',
  },
  {
    translations: {
      en: 'Guyana',
      sv: 'Guyana',
      de: 'Guyana',
      fr: 'Guyana',
      es: 'Guyana',
      ru: 'Гайана',
      uk: 'Гаяна',
      pl: 'Gujana',
    },
    flag: 'https://flagcdn.com/w320/gy.png',
    callingCode: '+592',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Haiti',
      sv: 'Haiti',
      de: 'Haiti',
      fr: 'Haïti',
      es: 'Haití',
      ru: 'Гаити',
      uk: 'Гаїті',
      pl: 'Haiti',
    },
    flag: 'https://flagcdn.com/w320/ht.png',
    callingCode: '+509',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Honduras',
      sv: 'Honduras',
      de: 'Honduras',
      fr: 'Honduras',
      es: 'Honduras',
      ru: 'Гондурас',
      uk: 'Гондурас',
      pl: 'Honduras',
    },
    flag: 'https://flagcdn.com/w320/hn.png',
    callingCode: '+504',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Hong Kong',
      sv: 'Hongkong',
      de: 'Hongkong',
      fr: 'Hong Kong',
      es: 'Hong Kong',
      ru: 'Гонконг',
      uk: 'Гонконг',
      pl: 'Hongkong',
    },
    flag: 'https://flagcdn.com/w320/hk.png',
    callingCode: '+852',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Hungary',
      sv: 'Ungern',
      de: 'Ungarn',
      fr: 'Hongrie',
      es: 'Hungría',
      ru: 'Венгрия',
      uk: 'Угорщина',
      pl: 'Węgry',
    },
    flag: 'https://flagcdn.com/w320/hu.png',
    callingCode: '+36',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Iceland',
      sv: 'Island',
      de: 'Island',
      fr: 'Islande',
      es: 'Islandia',
      ru: 'Исландия',
      uk: 'Ісландія',
      pl: 'Islandia',
    },
    flag: 'https://flagcdn.com/w320/is.png',
    callingCode: '+354',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'India',
      sv: 'Indien',
      de: 'Indien',
      fr: 'Inde',
      es: 'India',
      ru: 'Индия',
      uk: 'Індія',
      pl: 'Indie',
    },
    flag: 'https://flagcdn.com/w320/in.png',
    callingCode: '+91',
    phoneFormat: '(####)###-###',
  },
  {
    translations: {
      en: 'Indonesia',
      sv: 'Indonesien',
      de: 'Indonesien',
      fr: 'Indonésie',
      es: 'Indonesia',
      ru: 'Индонезия',
      uk: 'Індонезія',
      pl: 'Indonezja',
    },
    flag: 'https://flagcdn.com/w320/id.png',
    callingCode: '+62',
    phoneFormat: [
      '(8##)###-####',
      '##-###-##',
      '##-###-###',
      '##-###-####',
      '(8##)###-###',
      '(8##)###-##-###',
    ],
  },
  {
    translations: {
      en: 'Iran',
      sv: 'Iran',
      de: 'Iran',
      fr: 'Iran',
      es: 'Irán',
      ru: 'Иран',
      uk: 'Іран',
      pl: 'Iran',
    },
    flag: 'https://flagcdn.com/w320/ir.png',
    callingCode: '+98',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Iraq',
      sv: 'Irak',
      de: 'Irak',
      fr: 'Irak',
      es: 'Irak',
      ru: 'Ирак',
      uk: 'Ірак',
      pl: 'Irak',
    },
    flag: 'https://flagcdn.com/w320/iq.png',
    callingCode: '+964',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Ireland',
      sv: 'Irland',
      de: 'Irland',
      fr: 'Irlande',
      es: 'Irlanda',
      ru: 'Ирландия',
      uk: 'Ірландія',
      pl: 'Irlandia',
    },
    flag: 'https://flagcdn.com/w320/ie.png',
    callingCode: '+353',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Israel',
      sv: 'Israel',
      de: 'Israel',
      fr: 'Israël',
      es: 'Israel',
      ru: 'Израиль',
      uk: 'Ізраїль',
      pl: 'Izrael',
    },
    flag: 'https://flagcdn.com/w320/il.png',
    callingCode: '+972',
    phoneFormat: ['5#-###-####', '#-###-####'],
  },
  {
    translations: {
      en: 'Italy',
      sv: 'Italien',
      de: 'Italien',
      fr: 'Italie',
      es: 'Italia',
      ru: 'Италия',
      uk: 'Італія',
      pl: 'Włochy',
    },
    flag: 'https://flagcdn.com/w320/it.png',
    callingCode: '+39',
    phoneFormat: '(###)####-###',
  },
  {
    translations: {
      en: 'Jamaica',
      sv: 'Jamaika',
      de: 'Jamaika',
      fr: 'Jamaïque',
      es: 'Jamaica',
      ru: 'Ямайка',
      uk: 'Ямайка',
      pl: 'Jamajka',
    },
    flag: 'https://flagcdn.com/w320/jm.png',
    callingCode: '+1876',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Japan',
      sv: 'Japan',
      de: 'Japan',
      fr: 'Japon',
      es: 'Japón',
      ru: 'Япония',
      uk: 'Японія',
      pl: 'Japonia',
    },
    flag: 'https://flagcdn.com/w320/jp.png',
    callingCode: '+81',
    phoneFormat: ['##-####-####', '(###)###-###'],
  },
  {
    translations: {
      en: 'Jordan',
      sv: 'Jordanien',
      de: 'Jordanien',
      fr: 'Jordanie',
      es: 'Jordania',
      ru: 'Иордания',
      uk: 'Йорданія',
      pl: 'Jordania',
    },
    flag: 'https://flagcdn.com/w320/jo.png',
    callingCode: '+962',
    phoneFormat: '#-####-####',
  },
  {
    translations: {
      en: 'Kazakhstan',
      sv: 'Kazakstan',
      de: 'Kasachstan',
      fr: 'Kazakhstan',
      es: 'Kazajistán',
      ru: 'Казахстан',
      uk: 'Казахстан',
      pl: 'Kazachstan',
    },
    flag: 'https://flagcdn.com/w320/kz.png',
    callingCode: '+7',
    phoneFormat: ['(6##)###-##-##', '(7##)###-##-##'],
  },
  {
    translations: {
      en: 'Kenya',
      sv: 'Kenya',
      de: 'Kenia',
      fr: 'Kenya',
      es: 'Kenia',
      ru: 'Кения',
      uk: 'Кенія',
      pl: 'Kenia',
    },
    flag: 'https://flagcdn.com/w320/ke.png',
    callingCode: '+254',
    phoneFormat: '###-######',
  },
  {
    translations: {
      en: 'Kiribati',
      sv: 'Kiribati',
      de: 'Kiribati',
      fr: 'Kiribati',
      es: 'Kiribati',
      ru: 'Кирибати',
      uk: 'Кірібаті',
      pl: 'Kiribati',
    },
    flag: 'https://flagcdn.com/w320/ki.png',
    callingCode: '+686',
    phoneFormat: '##-###',
  },
  {
    translations: {
      en: 'Kosovo',
      sv: 'Kosovo',
      de: 'Kosovo',
      fr: 'Kosovo',
      es: 'Kosovo',
      ru: 'Косово',
      uk: 'Косово',
      pl: 'Kosowo',
    },
    flag: 'https://flagcdn.com/w320/xk.png',
    callingCode: '+383',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Kuwait',
      sv: 'Kuwait',
      de: 'Kuwait',
      fr: 'Kuwait',
      es: 'Kuwait',
      ru: 'Кувейт',
      uk: 'Кувейт',
      pl: 'Kuwejt',
    },
    flag: 'https://flagcdn.com/w320/kw.png',
    callingCode: '+965',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Kyrgyzstan',
      sv: 'Kyrgyzstan',
      de: 'Kirgisistan',
      fr: 'Kirghizistan',
      es: 'Kirguistán',
      ru: 'Киргизия',
      uk: 'Киргизстан',
      pl: 'Kirgistan',
    },
    flag: 'https://flagcdn.com/w320/kg.png',
    callingCode: '+996',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Laos',
      sv: 'Laos',
      de: 'Laos',
      fr: 'Laos',
      es: 'Laos',
      ru: 'Лаос',
      uk: 'Лаос',
      pl: 'Laos',
    },
    flag: 'https://flagcdn.com/w320/la.png',
    callingCode: '+856',
    phoneFormat: ['##-###-###', '(20##)###-###'],
  },
  {
    translations: {
      en: 'Latvia',
      sv: 'Lettland',
      de: 'Lettland',
      fr: 'Lettonie',
      es: 'Letonia',
      ru: 'Латвия',
      uk: 'Латвія',
      pl: 'Łotwa',
    },
    flag: 'https://flagcdn.com/w320/lv.png',
    callingCode: '+371',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Lebanon',
      sv: 'Libanon',
      de: 'Libanon',
      fr: 'Liban',
      es: 'Líbano',
      ru: 'Ливан',
      uk: 'Ліван',
      pl: 'Liban',
    },
    flag: 'https://flagcdn.com/w320/lb.png',
    callingCode: '+961',
    phoneFormat: ['#-###-###', '##-###-###'],
  },
  {
    translations: {
      en: 'Lesotho',
      sv: 'Lesotho',
      de: 'Lesotho',
      fr: 'Lesotho',
      es: 'Lesoto',
      ru: 'Лесото',
      uk: 'Лесото',
      pl: 'Lesotho',
    },
    flag: 'https://flagcdn.com/w320/ls.png',
    callingCode: '+266',
    phoneFormat: '#-###-####',
  },
  {
    translations: {
      en: 'Liberia',
      sv: 'Liberia',
      de: 'Liberia',
      fr: 'Libéria',
      es: 'Liberia',
      ru: 'Либерия',
      uk: 'Ліберія',
      pl: 'Liberia',
    },
    flag: 'https://flagcdn.com/w320/lr.png',
    callingCode: '+231',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Libya',
      sv: 'Libyen',
      de: 'Libyen',
      fr: 'Libye',
      es: 'Libia',
      ru: 'Ливия',
      uk: 'Лівія',
      pl: 'Libia',
    },
    flag: 'https://flagcdn.com/w320/ly.png',
    callingCode: '+218',
    phoneFormat: ['##-###-###', '21-###-####'],
  },
  {
    translations: {
      en: 'Liechtenstein',
      sv: 'Liechtenstein',
      de: 'Liechtenstein',
      fr: 'Liechtenstein',
      es: 'Liechtenstein',
      ru: 'Лихтенштейн',
      uk: 'Ліхтенштейн',
      pl: 'Liechtenstein',
    },
    flag: 'https://flagcdn.com/w320/li.png',
    callingCode: '+423',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Lithuania',
      sv: 'Litauen',
      de: 'Litauen',
      fr: 'Lituanie',
      es: 'Lituania',
      ru: 'Литва',
      uk: 'Литва',
      pl: 'Litwa',
    },
    flag: 'https://flagcdn.com/w320/lt.png',
    callingCode: '+370',
    phoneFormat: '(###)##-###',
  },
  {
    translations: {
      en: 'Luxembourg',
      sv: 'Luxemburg',
      de: 'Luxemburg',
      fr: 'Luxembourg',
      es: 'Luxemburgo',
      ru: 'Люксембург',
      uk: 'Люксембург',
      pl: 'Luksemburg',
    },
    flag: 'https://flagcdn.com/w320/lu.png',
    callingCode: '+352',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Macau',
      sv: 'Macau',
      de: 'Macao',
      fr: 'Macao',
      es: 'Macao',
      ru: 'Макао',
      uk: 'Макао',
      pl: 'Makau',
    },
    flag: 'https://flagcdn.com/w320/mo.png',
    callingCode: '+853',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'North Macedonia',
      sv: 'Nordmakedonien',
      de: 'Nordmazedonien',
      fr: 'Macédoine du Nord',
      es: 'Macedonia del Norte',
      ru: 'Северная Македония',
      uk: 'Північна Македонія',
      pl: 'Macedonia Północna',
    },
    flag: 'https://flagcdn.com/w320/mk.png',
    callingCode: '+389',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Madagascar',
      sv: 'Madagaskar',
      de: 'Madagaskar',
      fr: 'Madagascar',
      es: 'Madagascar',
      ru: 'Мадагаскар',
      uk: 'Мадагаскар',
      pl: 'Madagaskar',
    },
    flag: 'https://flagcdn.com/w320/mg.png',
    callingCode: '+261',
    phoneFormat: '##-##-#####',
  },
  {
    translations: {
      en: 'Malawi',
      sv: 'Malawi',
      de: 'Malawi',
      fr: 'Malawi',
      es: 'Malawi',
      ru: 'Малави',
      uk: 'Малаві',
      pl: 'Malawi',
    },
    flag: 'https://flagcdn.com/w320/mw.png',
    callingCode: '+265',
    phoneFormat: ['1-###-###', '#-####-####'],
  },
  {
    translations: {
      en: 'Malaysia',
      sv: 'Malaysien',
      de: 'Malaysia',
      fr: 'Malaisie',
      es: 'Malasia',
      ru: 'Малайзия',
      uk: 'Малайзія',
      pl: 'Malezja',
    },
    flag: 'https://flagcdn.com/w320/my.png',
    callingCode: '+60',
    phoneFormat: ['##-###-####', '(###)###-###', '##-###-###', '#-###-###'],
  },
  {
    translations: {
      en: 'Maldives',
      sv: 'Maldiverna',
      de: 'Maldiven',
      fr: 'Maldives',
      es: 'Maldivas',
      ru: 'Мальдивы',
      uk: 'Мальдіви',
      pl: 'Malediwy',
    },
    flag: 'https://flagcdn.com/w320/mv.png',
    callingCode: '+960',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Mali',
      sv: 'Mali',
      de: 'Mali',
      fr: 'Mali',
      es: 'Mali',
      ru: 'Мали',
      uk: 'Малі',
      pl: 'Mali',
    },
    flag: 'https://flagcdn.com/w320/ml.png',
    callingCode: '+223',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Malta',
      sv: 'Malta',
      de: 'Malta',
      fr: 'Malte',
      es: 'Malta',
      ru: 'Мальта',
      uk: 'Мальта',
      pl: 'Malta',
    },
    flag: 'https://flagcdn.com/w320/mt.png',
    callingCode: '+356',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Marshall Islands',
      sv: 'Marshallöarna',
      de: 'Marshallinseln',
      fr: 'Îles Marshall',
      es: 'Islas Marshall',
      ru: 'Маршалловы Острова',
      uk: 'Маршаллові Острови',
      pl: 'Wyspy Marshalla',
    },
    flag: 'https://flagcdn.com/w320/mh.png',
    callingCode: '+692',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Martinique',
      sv: 'Martinique',
      de: 'Martinique',
      fr: 'Martinique',
      es: 'Martinica',
      ru: 'Мартиника',
      uk: 'Мартініка',
      pl: 'Martynika',
    },
    flag: 'https://flagcdn.com/w320/mq.png',
    callingCode: '+596',
    phoneFormat: '(###)##-##-##',
  },
  {
    translations: {
      en: 'Mauritania',
      sv: 'Mauretanien',
      de: 'Mauretanien',
      fr: 'Mauritanie',
      es: 'Mauritania',
      ru: 'Мавритания',
      uk: 'Мавританія',
      pl: 'Mauretania',
    },
    flag: 'https://flagcdn.com/w320/mr.png',
    callingCode: '+222',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Mauritius',
      sv: 'Mauritius',
      de: 'Mauritius',
      fr: 'Maurice',
      es: 'Mauricio',
      ru: 'Маврикий',
      uk: 'Маврикій',
      pl: 'Mauritius',
    },
    flag: 'https://flagcdn.com/w320/mu.png',
    callingCode: '+230',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Mexico',
      sv: 'Mexiko',
      de: 'Mexiko',
      fr: 'Mexique',
      es: 'México',
      ru: 'Мексика',
      uk: 'Мексика',
      pl: 'Meksyk',
    },
    flag: 'https://flagcdn.com/w320/mx.png',
    callingCode: '+52',
    phoneFormat: ['(###)###-####', '##-##-####'],
  },
  {
    translations: {
      en: 'Micronesia',
      sv: 'Mikronesiska federationen',
      de: 'Mikronesien',
      fr: 'Micronésie',
      es: 'Micronesia',
      ru: 'Микронезия',
      uk: 'Мікронезія',
      pl: 'Mikronezja',
    },
    flag: 'https://flagcdn.com/w320/fm.png',
    callingCode: '+691',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Moldova',
      sv: 'Moldavien',
      de: 'Moldau',
      fr: 'Moldavie',
      es: 'Moldavia',
      ru: 'Молдова',
      uk: 'Молдова',
      pl: 'Mołdawia',
    },
    flag: 'https://flagcdn.com/w320/md.png',
    callingCode: '+373',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Monaco',
      sv: 'Monaco',
      de: 'Monaco',
      fr: 'Monaco',
      es: 'Mónaco',
      ru: 'Монако',
      uk: 'Монако',
      pl: 'Monako',
    },
    flag: 'https://flagcdn.com/w320/mc.png',
    callingCode: '+377',
    phoneFormat: ['(###)###-###', '##-###-###'],
  },
  {
    translations: {
      en: 'Mongolia',
      sv: 'Mongoliet',
      de: 'Mongolei',
      fr: 'Mongolie',
      es: 'Mongolia',
      ru: 'Монголия',
      uk: 'Монголія',
      pl: 'Mongolia',
    },
    flag: 'https://flagcdn.com/w320/mn.png',
    callingCode: '+976',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Montenegro',
      sv: 'Montenegro',
      de: 'Montenegro',
      fr: 'Monténégro',
      es: 'Montenegro',
      ru: 'Черногория',
      uk: 'Чорногорія',
      pl: 'Czarnogóra',
    },
    flag: 'https://flagcdn.com/w320/me.png',
    callingCode: '+382',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Morocco',
      sv: 'Marocko',
      de: 'Marokko',
      fr: 'Maroc',
      es: 'Marruecos',
      ru: 'Марокко',
      uk: 'Марокко',
      pl: 'Maroko',
    },
    flag: 'https://flagcdn.com/w320/ma.png',
    callingCode: '+212',
    phoneFormat: '##-####-###',
  },
  {
    translations: {
      en: 'Mozambique',
      sv: 'Moçambique',
      de: 'Mosambik',
      fr: 'Mozambique',
      es: 'Mozambique',
      ru: 'Мозамбик',
      uk: 'Мозамбік',
      pl: 'Mozambik',
    },
    flag: 'https://flagcdn.com/w320/mz.png',
    callingCode: '+258',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Myanmar',
      sv: 'Myanmar',
      de: 'Myanmar',
      fr: 'Myanmar',
      es: 'Myanmar',
      ru: 'Мьянма',
      uk: "М'янма",
      pl: 'Mjanma (Birma)',
    },
    flag: 'https://flagcdn.com/w320/mm.png',
    callingCode: '+95',
    phoneFormat: ['##-###-###', '#-###-###', '###-###'],
  },
  {
    translations: {
      en: 'Namibia',
      sv: 'Namibia',
      de: 'Namibia',
      fr: 'Namibie',
      es: 'Namibia',
      ru: 'Намибия',
      uk: 'Намібія',
      pl: 'Namibia',
    },
    flag: 'https://flagcdn.com/w320/na.png',
    callingCode: '+264',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Nauru',
      sv: 'Nauru',
      de: 'Nauru',
      fr: 'Nauru',
      es: 'Nauru',
      ru: 'Науру',
      uk: 'Науру',
      pl: 'Nauru',
    },
    flag: 'https://flagcdn.com/w320/nr.png',
    callingCode: '+674',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Nepal',
      sv: 'Nepal',
      de: 'Nepal',
      fr: 'Népal',
      es: 'Nepal',
      ru: 'Непал',
      uk: 'Непал',
      pl: 'Nepal',
    },
    flag: 'https://flagcdn.com/w320/np.png',
    callingCode: '+977',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Netherlands',
      sv: 'Nederländerna',
      de: 'Niederlande',
      fr: 'Pays-Bas',
      es: 'Países Bajos',
      ru: 'Нидерланды',
      uk: 'Нідерланди',
      pl: 'Holandia',
    },
    flag: 'https://flagcdn.com/w320/nl.png',
    callingCode: '+31',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'New Zealand',
      sv: 'Nya Zeeland',
      de: 'Neuseeland',
      fr: 'Nouvelle-Zélande',
      es: 'Nueva Zelanda',
      ru: 'Новая Зеландия',
      uk: 'Нова Зеландія',
      pl: 'Nowa Zelandia',
    },
    flag: 'https://flagcdn.com/w320/nz.png',
    callingCode: '+64',
    phoneFormat: ['(###)###-###', '##-###-###', '(###)###-####'],
  },
  {
    translations: {
      en: 'Nicaragua',
      sv: 'Nicaragua',
      de: 'Nicaragua',
      fr: 'Nicaragua',
      es: 'Nicaragua',
      ru: 'Никарагуа',
      uk: 'Нікарагуа',
      pl: 'Nikaragua',
    },
    flag: 'https://flagcdn.com/w320/ni.png',
    callingCode: '+505',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Niger',
      sv: 'Niger',
      de: 'Niger',
      fr: 'Niger',
      es: 'Níger',
      ru: 'Нигер',
      uk: 'Нігер',
      pl: 'Niger',
    },
    flag: 'https://flagcdn.com/w320/ne.png',
    callingCode: '+227',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Nigeria',
      sv: 'Nigeria',
      de: 'Nigeria',
      fr: 'Nigéria',
      es: 'Nigeria',
      ru: 'Нигерия',
      uk: 'Нігерія',
      pl: 'Nigeria',
    },
    flag: 'https://flagcdn.com/w320/ng.png',
    callingCode: '+234',
    phoneFormat: ['(###)###-####', '##-###-###', '##-###-##', '(###)###-####'],
  },
  {
    translations: {
      en: 'Norway',
      sv: 'Norge',
      de: 'Norwegen',
      fr: 'Norvège',
      es: 'Noruega',
      ru: 'Норвегия',
      uk: 'Норвегія',
      pl: 'Norwegia',
    },
    flag: 'https://flagcdn.com/w320/no.png',
    callingCode: '+47',
    phoneFormat: '(###)##-###',
  },
  {
    translations: {
      en: 'Oman',
      sv: 'Oman',
      de: 'Oman',
      fr: 'Oman',
      es: 'Omán',
      ru: 'Оман',
      uk: 'Оман',
      pl: 'Oman',
    },
    flag: 'https://flagcdn.com/w320/om.png',
    callingCode: '+968',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Pakistan',
      sv: 'Pakistan',
      de: 'Pakistan',
      fr: 'Pakistan',
      es: 'Pakistán',
      ru: 'Пакистан',
      uk: 'Пакистан',
      pl: 'Pakistan',
    },
    flag: 'https://flagcdn.com/w320/pk.png',
    callingCode: '+92',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Palau',
      sv: 'Palau',
      de: 'Palau',
      fr: 'Palaos',
      es: 'Palaos',
      ru: 'Палау',
      uk: 'Палау',
      pl: 'Palau',
    },
    flag: 'https://flagcdn.com/w320/pw.png',
    callingCode: '+680',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Palestine',
      sv: 'Palestina',
      de: 'Palästina',
      fr: 'Palestine',
      es: 'Palestina',
      ru: 'Палестина',
      uk: 'Палестина',
      pl: 'Palestyna',
    },
    flag: 'https://flagcdn.com/w320/ps.png',
    callingCode: '+970',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Panama',
      sv: 'Panama',
      de: 'Panama',
      fr: 'Panama',
      es: 'Panamá',
      ru: 'Панама',
      uk: 'Панама',
      pl: 'Panama',
    },
    flag: 'https://flagcdn.com/w320/pa.png',
    callingCode: '+507',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Papua New Guinea',
      sv: 'Papua Nya Guinea',
      de: 'Papua-Neuguinea',
      fr: 'Papouasie-Nouvelle-Guinée',
      es: 'Papúa Nueva Guinea',
      ru: 'Папуа — Новая Гвинея',
      uk: 'Папуа Нова Гвінея',
      pl: 'Papua-Nowa Gwinea',
    },
    flag: 'https://flagcdn.com/w320/pg.png',
    callingCode: '+675',
    phoneFormat: '(###)##-###',
  },
  {
    translations: {
      en: 'Paraguay',
      sv: 'Paraguay',
      de: 'Paraguay',
      fr: 'Paraguay',
      es: 'Paraguay',
      ru: 'Парагвай',
      uk: 'Парагвай',
      pl: 'Paragwaj',
    },
    flag: 'https://flagcdn.com/w320/py.png',
    callingCode: '+595',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Peru',
      sv: 'Peru',
      de: 'Peru',
      fr: 'Pérou',
      es: 'Perú',
      ru: 'Перу',
      uk: 'Перу',
      pl: 'Peru',
    },
    flag: 'https://flagcdn.com/w320/pe.png',
    callingCode: '+51',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Philippines',
      sv: 'Filippinerna',
      de: 'Philippinen',
      fr: 'Philippines',
      es: 'Filipinas',
      ru: 'Филиппины',
      uk: 'Філіппіни',
      pl: 'Filipiny',
    },
    flag: 'https://flagcdn.com/w320/ph.png',
    callingCode: '+63',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Poland',
      sv: 'Polen',
      de: 'Polen',
      fr: 'Pologne',
      es: 'Polonia',
      ru: 'Польша',
      uk: 'Польща',
      pl: 'Polska',
    },
    flag: 'https://flagcdn.com/w320/pl.png',
    callingCode: '+48',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Portugal',
      sv: 'Portugal',
      de: 'Portugal',
      fr: 'Portugal',
      es: 'Portugal',
      ru: 'Португалия',
      uk: 'Португалія',
      pl: 'Portugalia',
    },
    flag: 'https://flagcdn.com/w320/pt.png',
    callingCode: '+351',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Puerto Rico',
      sv: 'Puerto Rico',
      de: 'Puerto Rico',
      fr: 'Porto Rico',
      es: 'Puerto Rico',
      ru: 'Пуэрто-Рико',
      uk: 'Пуерто-Рико',
      pl: 'Portoryko',
    },
    flag: 'https://flagcdn.com/w320/pr.png',
    callingCode: '+1787',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Qatar',
      sv: 'Qatar',
      de: 'Katar',
      fr: 'Qatar',
      es: 'Catar',
      ru: 'Катар',
      uk: 'Катар',
      pl: 'Katar',
    },
    flag: 'https://flagcdn.com/w320/qa.png',
    callingCode: '+974',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Réunion',
      sv: 'Réunion',
      de: 'Réunion',
      fr: 'La Réunion',
      es: 'Reunión',
      ru: 'Реюньон',
      uk: 'Реюньйон',
      pl: 'Reunion',
    },
    flag: 'https://flagcdn.com/w320/re.png',
    callingCode: '+262',
    phoneFormat: '#####-####',
  },
  {
    translations: {
      en: 'Romania',
      sv: 'Rumänien',
      de: 'Rumänien',
      fr: 'Roumanie',
      es: 'Rumania',
      ru: 'Румыния',
      uk: 'Румунія',
      pl: 'Rumunia',
    },
    flag: 'https://flagcdn.com/w320/ro.png',
    callingCode: '+40',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Russia',
      sv: 'Ryssland',
      de: 'Russland',
      fr: 'Russie',
      es: 'Rusia',
      ru: 'Россия',
      uk: 'Росія',
      pl: 'Rosja',
    },
    flag: 'https://flagcdn.com/w320/ru.png',
    callingCode: '+7',
    phoneFormat: '(###)###-##-##',
  },
  {
    translations: {
      en: 'Rwanda',
      sv: 'Rwanda',
      de: 'Ruanda',
      fr: 'Rwanda',
      es: 'Ruanda',
      ru: 'Руанда',
      uk: 'Руанда',
      pl: 'Rwanda',
    },
    flag: 'https://flagcdn.com/w320/rw.png',
    callingCode: '+250',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Saint Kitts and Nevis',
      sv: 'Saint Kitts och Nevis',
      de: 'St. Kitts und Nevis',
      fr: 'Saint-Christophe-et-Niévès',
      es: 'San Cristóbal y Nieves',
      ru: 'Сент-Китс и Невис',
      uk: 'Сент-Кітс і Невіс',
      pl: 'Saint Kitts i Nevis',
    },
    flag: 'https://flagcdn.com/w320/kn.png',
    callingCode: '+1869',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Saint Lucia',
      sv: 'Saint Lucia',
      de: 'St. Lucia',
      fr: 'Sainte-Lucie',
      es: 'Santa Lucía',
      ru: 'Сент-Люсия',
      uk: 'Сент-Люсія',
      pl: 'Saint Lucia',
    },
    flag: 'https://flagcdn.com/w320/lc.png',
    callingCode: '+1758',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Saint Vincent and the Grenadines',
      sv: 'Saint Vincent och Grenadinerna',
      de: 'St. Vincent und die Grenadinen',
      fr: 'Saint-Vincent-et-les-Grenadines',
      es: 'San Vicente y las Granadinas',
      ru: 'Сент-Винсент и Гренадины',
      uk: 'Сент-Вінсент і Гренадини',
      pl: 'Saint Vincent i Grenadyny',
    },
    flag: 'https://flagcdn.com/w320/vc.png',
    callingCode: '+1784',
    phoneFormat: '###-####',
  },
  {
    translations: {
      en: 'Samoa',
      sv: 'Samoa',
      de: 'Samoa',
      fr: 'Samoa',
      es: 'Samoa',
      ru: 'Самоа',
      uk: 'Самоа',
      pl: 'Samoa',
    },
    flag: 'https://flagcdn.com/w320/ws.png',
    callingCode: '+685',
    phoneFormat: '##-####',
  },
  {
    translations: {
      en: 'San Marino',
      sv: 'San Marino',
      de: 'San Marino',
      fr: 'Saint-Marin',
      es: 'San Marino',
      ru: 'Сан-Марино',
      uk: 'Сан-Марино',
      pl: 'San Marino',
    },
    flag: 'https://flagcdn.com/w320/sm.png',
    callingCode: '+378',
    phoneFormat: '####-######',
  },
  {
    translations: {
      en: 'São Tomé and Príncipe',
      sv: 'São Tomé och Príncipe',
      de: 'São Tomé und Príncipe',
      fr: 'São Tomé-et-Príncipe',
      es: 'São Tomé y Príncipe',
      ru: 'Сан-Томе и Принсипи',
      uk: 'Сан-Томе і Принсіпі',
      pl: 'Wyspy Świętego Tomasza i Książęca',
    },
    flag: 'https://flagcdn.com/w320/st.png',
    callingCode: '+239',
    phoneFormat: '##-#####',
  },
  {
    translations: {
      en: 'Saudi Arabia',
      sv: 'Saudiarabien',
      de: 'Saudi-Arabien',
      fr: 'Arabie Saoudite',
      es: 'Arabia Saudita',
      ru: 'Саудовская Аравия',
      uk: 'Саудівська Аравія',
      pl: 'Arabia Saudyjska',
    },
    flag: 'https://flagcdn.com/w320/sa.png',
    callingCode: '+966',
    phoneFormat: ['5-####-####', '#-###-####'],
  },
  {
    translations: {
      en: 'Senegal',
      sv: 'Senegal',
      de: 'Senegal',
      fr: 'Sénégal',
      es: 'Senegal',
      ru: 'Сенегал',
      uk: 'Сенегал',
      pl: 'Senegal',
    },
    flag: 'https://flagcdn.com/w320/sn.png',
    callingCode: '+221',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Serbia',
      sv: 'Serbien',
      de: 'Serbien',
      fr: 'Serbie',
      es: 'Serbia',
      ru: 'Сербия',
      uk: 'Сербія',
      pl: 'Serbia',
    },
    flag: 'https://flagcdn.com/w320/rs.png',
    callingCode: '+381',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Seychelles',
      sv: 'Seychellerna',
      de: 'Seychellen',
      fr: 'Seychelles',
      es: 'Seychelles',
      ru: 'Сейшельские Острова',
      uk: 'Сейшельські Острови',
      pl: 'Seszele',
    },
    flag: 'https://flagcdn.com/w320/sc.png',
    callingCode: '+248',
    phoneFormat: '#-###-###',
  },
  {
    translations: {
      en: 'Sierra Leone',
      sv: 'Sierra Leone',
      de: 'Sierra Leone',
      fr: 'Sierra Leone',
      es: 'Sierra Leona',
      ru: 'Сьерра-Леоне',
      uk: 'Сьєрра-Леоне',
      pl: 'Sierra Leone',
    },
    flag: 'https://flagcdn.com/w320/sl.png',
    callingCode: '+232',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Singapore',
      sv: 'Singapore',
      de: 'Singapur',
      fr: 'Singapour',
      es: 'Singapur',
      ru: 'Сингапур',
      uk: 'Сінгапур',
      pl: 'Singapur',
    },
    flag: 'https://flagcdn.com/w320/sg.png',
    callingCode: '+65',
    phoneFormat: '####-####',
  },
  {
    translations: {
      en: 'Slovakia',
      sv: 'Slovakien',
      de: 'Slowakei',
      fr: 'Slovaquie',
      es: 'Eslovaquia',
      ru: 'Словакия',
      uk: 'Словаччина',
      pl: 'Słowacja',
    },
    flag: 'https://flagcdn.com/w320/sk.png',
    callingCode: '+421',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Slovenia',
      sv: 'Slovenien',
      de: 'Slowenien',
      fr: 'Slovénie',
      es: 'Eslovenia',
      ru: 'Словения',
      uk: 'Словенія',
      pl: 'Słowenia',
    },
    flag: 'https://flagcdn.com/w320/si.png',
    callingCode: '+386',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Solomon Islands',
      sv: 'Salomonöarna',
      de: 'Salomonen',
      fr: 'Îles Salomon',
      es: 'Islas Salomón',
      ru: 'Соломоновы Острова',
      uk: 'Соломонові Острови',
      pl: 'Wyspy Salomona',
    },
    flag: 'https://flagcdn.com/w320/sb.png',
    callingCode: '+677',
    phoneFormat: ['###-####', '#####'],
  },
  {
    translations: {
      en: 'Somalia',
      sv: 'Somalia',
      de: 'Somalia',
      fr: 'Somalie',
      es: 'Somalia',
      ru: 'Сомали',
      uk: 'Сомалія',
      pl: 'Somalia',
    },
    flag: 'https://flagcdn.com/w320/so.png',
    callingCode: '+252',
    phoneFormat: ['##-###-###', '#-###-###', '#-###-###'],
  },
  {
    translations: {
      en: 'South Africa',
      sv: 'Sydafrika',
      de: 'Südafrika',
      fr: 'Afrique du Sud',
      es: 'Sudáfrica',
      ru: 'Южная Африка',
      uk: 'Південноафриканська Республіка',
      pl: 'Republika Południowej Afryki',
    },
    flag: 'https://flagcdn.com/w320/za.png',
    callingCode: '+27',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'South Korea',
      sv: 'Sydkorea',
      de: 'Südkorea',
      fr: 'Corée du Sud',
      es: 'Corea del Sur',
      ru: 'Южная Корея',
      uk: 'Південна Корея',
      pl: 'Korea Południowa',
    },
    flag: 'https://flagcdn.com/w320/kr.png',
    callingCode: '+82',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'South Sudan',
      sv: 'Sydsudan',
      de: 'Südsudan',
      fr: 'Soudan du Sud',
      es: 'Sudán del Sur',
      ru: 'Южный Судан',
      uk: 'Південний Судан',
      pl: 'Sudan Południowy',
    },
    flag: 'https://flagcdn.com/w320/ss.png',
    callingCode: '+211',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Spain',
      sv: 'Spanien',
      de: 'Spanien',
      fr: 'Espagne',
      es: 'España',
      ru: 'Испания',
      uk: 'Іспанія',
      pl: 'Hiszpania',
    },
    flag: 'https://flagcdn.com/w320/es.png',
    callingCode: '+34',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Sri Lanka',
      sv: 'Sri Lanka',
      de: 'Sri Lanka',
      fr: 'Sri Lanka',
      es: 'Sri Lanka',
      ru: 'Шри-Ланка',
      uk: 'Шрі-Ланка',
      pl: 'Sri Lanka',
    },
    flag: 'https://flagcdn.com/w320/lk.png',
    callingCode: '+94',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Sudan',
      sv: 'Sudan',
      de: 'Sudan',
      fr: 'Soudan',
      es: 'Sudán',
      ru: 'Судан',
      uk: 'Судан',
      pl: 'Sudan',
    },
    flag: 'https://flagcdn.com/w320/sd.png',
    callingCode: '+249',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Suriname',
      sv: 'Surinam',
      de: 'Surinam',
      fr: 'Suriname',
      es: 'Surinam',
      ru: 'Суринам',
      uk: 'Суринам',
      pl: 'Surinam',
    },
    flag: 'https://flagcdn.com/w320/sr.png',
    callingCode: '+597',
    phoneFormat: '###-###',
  },
  {
    translations: {
      en: 'Eswatini',
      sv: 'Eswatini',
      de: 'Eswatini',
      fr: 'Eswatini',
      es: 'Esuatini',
      ru: 'Эсватини',
      uk: 'Есватіні',
      pl: 'Eswatini',
    },
    flag: 'https://flagcdn.com/w320/sz.png',
    callingCode: '+268',
    phoneFormat: '##-##-####',
  },
  {
    translations: {
      en: 'Sweden',
      sv: 'Sverige',
      de: 'Schweden',
      fr: 'Suède',
      es: 'Suecia',
      ru: 'Швеция',
      uk: 'Швеція',
      pl: 'Szwecja',
    },
    flag: 'https://flagcdn.com/w320/se.png',
    callingCode: '+46',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Switzerland',
      sv: 'Schweiz',
      de: 'Schweiz',
      fr: 'Suisse',
      es: 'Suiza',
      ru: 'Швейцария',
      uk: 'Швейцарія',
      pl: 'Szwajcaria',
    },
    flag: 'https://flagcdn.com/w320/ch.png',
    callingCode: '+41',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Syria',
      sv: 'Syrien',
      de: 'Syrien',
      fr: 'Syrie',
      es: 'Siria',
      ru: 'Сирия',
      uk: 'Сирія',
      pl: 'Syria',
    },
    flag: 'https://flagcdn.com/w320/sy.png',
    callingCode: '+963',
    phoneFormat: '##-####-###',
  },
  {
    translations: {
      en: 'Taiwan',
      sv: 'Taiwan',
      de: 'Taiwan',
      fr: 'Taïwan',
      es: 'Taiwán',
      ru: 'Тайвань',
      uk: 'Тайвань',
      pl: 'Tajwan',
    },
    flag: 'https://flagcdn.com/w320/tw.png',
    callingCode: '+886',
    phoneFormat: ['####-####', '#-####-####'],
  },
  {
    translations: {
      en: 'Tajikistan',
      sv: 'Tajikistan',
      de: 'Tadschikistan',
      fr: 'Tadjikistan',
      es: 'Tayikistán',
      ru: 'Таджикистан',
      uk: 'Таджикистан',
      pl: 'Tadżykistan',
    },
    flag: 'https://flagcdn.com/w320/tj.png',
    callingCode: '+992',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Tanzania',
      sv: 'Tanzania',
      de: 'Tansania',
      fr: 'Tanzanie',
      es: 'Tanzania',
      ru: 'Танзания',
      uk: 'Танзанія',
      pl: 'Tanzania',
    },
    flag: 'https://flagcdn.com/w320/tz.png',
    callingCode: '+255',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Thailand',
      sv: 'Thailand',
      de: 'Thailand',
      fr: 'Thaïlande',
      es: 'Tailandia',
      ru: 'Таиланд',
      uk: 'Таїланд',
      pl: 'Tajlandia',
    },
    flag: 'https://flagcdn.com/w320/th.png',
    callingCode: '+66',
    phoneFormat: ['##-###-####', '##-###-###'],
  },
  {
    translations: {
      en: 'Timor-Leste',
      sv: 'Östtimor',
      de: 'Osttimor',
      fr: 'Timor oriental',
      es: 'Timor-Leste',
      ru: 'Тимор-Лесте',
      uk: 'Східний Тимор',
      pl: 'Timor Wschodni',
    },
    flag: 'https://flagcdn.com/w320/tl.png',
    callingCode: '+670',
    phoneFormat: ['###-####', '77#-#####', '78#-#####'],
  },
  {
    translations: {
      en: 'Tunisia',
      sv: 'Tunisien',
      de: 'Tunesien',
      fr: 'Tunisie',
      es: 'Túnez',
      ru: 'Тунис',
      uk: 'Туніс',
      pl: 'Tunezja',
    },
    flag: 'https://flagcdn.com/w320/tn.png',
    callingCode: '+216',
    phoneFormat: '##-###-###',
  },
  {
    translations: {
      en: 'Turkey',
      sv: 'Turkiet',
      de: 'Türkei',
      fr: 'Turquie',
      es: 'Turquía',
      ru: 'Турция',
      uk: 'Туреччина',
      pl: 'Turcja',
    },
    flag: 'https://flagcdn.com/w320/tr.png',
    callingCode: '+90',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Turkmenistan',
      sv: 'Turkmenistan',
      de: 'Turkmenistan',
      fr: 'Turkménistan',
      es: 'Turkmenistán',
      ru: 'Туркменистан',
      uk: 'Туркменістан',
      pl: 'Turkmenistan',
    },
    flag: 'https://flagcdn.com/w320/tm.png',
    callingCode: '+993',
    phoneFormat: '#-###-####',
  },
  {
    translations: {
      en: 'Tuvalu',
      sv: 'Tuvalu',
      de: 'Tuvalu',
      fr: 'Tuvalu',
      es: 'Tuvalu',
      ru: 'Тувалу',
      uk: 'Тувалу',
      pl: 'Tuvalu',
    },
    flag: 'https://flagcdn.com/w320/tv.png',
    callingCode: '+688',
    phoneFormat: ['90####', '2####'],
  },
  {
    translations: {
      en: 'Uganda',
      sv: 'Uganda',
      de: 'Uganda',
      fr: 'Ouganda',
      es: 'Uganda',
      ru: 'Уганда',
      uk: 'Уганда',
      pl: 'Uganda',
    },
    flag: 'https://flagcdn.com/w320/ug.png',
    callingCode: '+256',
    phoneFormat: '(###)###-###',
  },
  {
    translations: {
      en: 'Ukraine',
      sv: 'Ukraina',
      de: 'Ukraina',
      fr: 'Ukraine',
      es: 'Ucrania',
      ru: 'Украина',
      uk: 'Україна',
      pl: 'Ukraina',
    },
    flag: 'https://flagcdn.com/w320/ua.png',
    callingCode: '+380',
    phoneFormat: '(##)###-##-##',
  },
  {
    translations: {
      en: 'United Arab Emirates',
      sv: 'Förenade Arabemiraten',
      de: 'Vereinigte Arabische Emirate',
      fr: 'Émirats arabes unis',
      es: 'Emiratos Árabes Unidos',
      ru: 'Объединенные Арабские Эмираты',
      uk: "Об'єднані Арабські Емірати",
      pl: 'Zjednoczone Emiraty Arabskie',
    },
    flag: 'https://flagcdn.com/w320/ae.png',
    callingCode: '+971',
    phoneFormat: ['5#-###-####', '#-###-####'],
  },
  {
    translations: {
      en: 'United Kingdom',
      sv: 'Storbritannien',
      de: 'Vereinigtes Königreich',
      fr: 'Royaume-Uni',
      es: 'Reino Unido',
      ru: 'Великобритания',
      uk: 'Великобританія',
      pl: 'Wielka Brytania',
    },
    flag: 'https://flagcdn.com/w320/gb.png',
    callingCode: '+44',
    phoneFormat: '##-####-####',
  },
  {
    translations: {
      en: 'United States',
      sv: 'Förenta staterna',
      de: 'Vereinigte Staaten',
      fr: 'États-Unis',
      es: 'Estados Unidos',
      ru: 'Соединенные Штаты',
      uk: 'Сполучені Штати',
      pl: 'Stany Zjednoczone',
    },
    flag: 'https://flagcdn.com/w320/us.png',
    callingCode: '+1',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Uruguay',
      sv: 'Uruguay',
      de: 'Uruguay',
      fr: 'Uruguay',
      es: 'Uruguay',
      ru: 'Уругвай',
      uk: 'Уругвай',
      pl: 'Urugwaj',
    },
    flag: 'https://flagcdn.com/w320/uy.png',
    callingCode: '+598',
    phoneFormat: '#-###-##-##',
  },
  {
    translations: {
      en: 'Uzbekistan',
      sv: 'Usbekistan',
      de: 'Usbekistan',
      fr: 'Ouzbékistan',
      es: 'Uzbekistán',
      ru: 'Узбекистан',
      uk: 'Узбекистан',
      pl: 'Uzbekistan',
    },
    flag: 'https://flagcdn.com/w320/uz.png',
    callingCode: '+998',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Vanuatu',
      sv: 'Vanuatu',
      de: 'Vanuatu',
      fr: 'Vanuatu',
      es: 'Vanuatu',
      ru: 'Вануату',
      uk: 'Вануату',
      pl: 'Vanuatu',
    },
    flag: 'https://flagcdn.com/w320/vu.png',
    callingCode: '+678',
    phoneFormat: ['##-#####', '#####'],
  },
  {
    translations: {
      en: 'Vatican City',
      sv: 'Vatikanstaten',
      de: 'Vatikanstadt',
      fr: 'Vatican',
      es: 'Ciudad del Vaticano',
      ru: 'Ватикан',
      uk: 'Ватикан',
      pl: 'Watykan',
    },
    flag: 'https://flagcdn.com/w320/va.png',
    callingCode: '+39',
    phoneFormat: '6-698-#####',
  },
  {
    translations: {
      en: 'Venezuela',
      sv: 'Venezuela',
      de: 'Venezuela',
      fr: 'Venezuela',
      es: 'Venezuela',
      ru: 'Венесуэла',
      uk: 'Венесуела',
      pl: 'Wenezuela',
    },
    flag: 'https://flagcdn.com/w320/ve.png',
    callingCode: '+58',
    phoneFormat: '(###)###-####',
  },
  {
    translations: {
      en: 'Vietnam',
      sv: 'Vietnam',
      de: 'Vietnam',
      fr: 'Viêt Nam',
      es: 'Vietnam',
      ru: 'Вьетнам',
      uk: "В'єтнам",
      pl: 'Wietnam',
    },
    flag: 'https://flagcdn.com/w320/vn.png',
    callingCode: '+84',
    phoneFormat: ['##-####-###', '(###)####-###'],
  },
  {
    translations: {
      en: 'Yemen',
      sv: 'Jemen',
      de: 'Jemen',
      fr: 'Yémen',
      es: 'Yemen',
      ru: 'Йемен',
      uk: 'Ємен',
      pl: 'Jemen',
    },
    flag: 'https://flagcdn.com/w320/ye.png',
    callingCode: '+967',
    phoneFormat: ['###-###-###', '#-###-###', '##-###-###'],
  },
  {
    translations: {
      en: 'Zambia',
      sv: 'Zambia',
      de: 'Sambia',
      fr: 'Zambie',
      es: 'Zambia',
      ru: 'Замбия',
      uk: 'Замбія',
      pl: 'Zambia',
    },
    flag: 'https://flagcdn.com/w320/zm.png',
    callingCode: '+260',
    phoneFormat: '##-###-####',
  },
  {
    translations: {
      en: 'Zimbabwe',
      sv: 'Zimbabwe',
      de: 'Simbabwe',
      fr: 'Zimbabwe',
      es: 'Zimbabue',
      ru: 'Зимбабве',
      uk: 'Зімбабве',
      pl: 'Zimbabwe',
    },
    flag: 'https://flagcdn.com/w320/zw.png',
    callingCode: '+263',
    phoneFormat: '#-######',
  },
];

export default countriesList;
